name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # ✅ این خط اضافه شده

      - uses: Platane/snk@v3
        with:
          github_user_name: pooyasamimi
          outputs: dist/snake.svg

      - name: Commit and push snake.svg
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Action
          author_email: actions@github.com
          message: "Generate snake.svg"
          add: "dist/snake.svg"
